dw_commodities:
  outputs:
    dev:
      dbname: atomdb
      # host: dpg-csdar5d6l47c739n51c0-a.oregon-postgres.render.com
      # pass: ob0YZmmqB5CxwUiW8bnDUe8Ojs2GPrtS
      # port: 5432
      # schema: public
      # threads: 1
      # type: postgres
      # user: postgres123
      # type: postgres
      host: "{{ env_var('DB_HOST_PROD') }}"
      user: "{{ env_var('DB_USER_PROD') }}"
      password: "{{ env_var('DB_PASS_PROD' ) }}"
      port: "{{.env_var('DB_PORT_PROD')|int }}"
      dbname: "{{ env_var('DB_NAME_PROD' ) }}"
      schema: "{{ env_var('DB_SCHEMA_PROD') }}"
      threads: "{{ env_var('DB_THREADS_PROD' )| int }}"
      keepalives idle: 0
  target: dev